site_name: Safe Exam Browser Tutorial 
site_url: https://example.com/Tutorial_SEB/
theme:
  name: material
  language: es
  logo: images/Icono_TX.png
  favicon: http://fptxurdinaga.eus/wp-content/uploads/2022/10/favicon-96x96-1.png
  custom_dir: overrides
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.expand
  palette:
    - scheme: default
      primary: '#004c95'
      accent: '#e95f15'
      toggle:
        icon: material/brightness-7
        name: Aldatu modu ilunera
    - scheme: slate
      primary: '#004c95'
      accent: '#e95f15'
      toggle:
        icon: material/brightness-4
        name: Aldatu modu argira
extra_css:
- stylesheets/extra.css
extra_javascript:
- scripts/checkboxes.js
- javascripts/sidebar.js
plugins:
- search
- i18n:
    docs_structure: folder
    languages:
      - locale: es
        name: Español
        default: true
        nav: 
          - Inicio: index.md
          - '1. Introducción':
            - '1.1. ¿Qué es Safe Exam Browser?': introduccion/que_es_seb.md
          - '2. Instalación':
            - '2.1. Instalación de SEB': instalazioa/instalacion.md
          - '3. Configuración':
            - '3.1. Configuración Básica': configuracion/configuracion_basica.md
            - '3.2. Integración con Moodle': configuracion/integracion_moodle.md
            - '3.3. Archivos de Configuración .seb': configuracion/archivos_configuracion.md
      - locale: eu
        name: Euskara
        nav:
          - Hasiera: index.md
          - '1. Sarrera':
            - '1.1. Zer da Safe Exam Browser?': sarrera/zer_da_seb.md
          - '2. Instalazioa':
            - '2.1. SEB Instalazioa': instalazioa/instalatu.md
          - '3. Konfigurazioa':
            - '3.1. Konfigurazioa Oinarrizkoa': konfigurazioa/konfigurazioa_oinarria.md
            - '3.2. Moodle-rekin integrazioa': konfigurazioa/moodle_integrazioa.md
            - '3.3. Konfigurazio fitxategiak (.seb)': konfigurazioa/fitxategiak_konfigurazioa.md
markdown_extensions:
- admonition
- pymdownx.tasklist:
    clickable_checkbox: true
    custom_checkbox: true
- toc:
    permalink: true
- footnotes
- tables
# Configuración de navegación principal (para compatibilidad)
# La navegación real ahora está definida en la sección de idiomas
nav:
  - Inicio: index.md
  - '1. Introducción':
    - '1.1. ¿Qué es Safe Exam Browser?': introduccion/que_es_seb.md
  - '2. Instalación':
    - '2.1. Instalación de SEB': instalacion/instalacion.md
  - '3. Configuración':
    - '3.1. Configuración Básica': configuracion/configuracion_basica.md
    - '3.2. Integración con Moodle': configuracion/integracion_moodle.md
