site_name: Safe Exam Browser Tutorial - 2025-2026
site_url: https://example.com/Tutorial_SEB/
theme:
  name: material
  language: eu
  logo: images/logo.png
  favicon: http://fptxurdinaga.eus/wp-content/uploads/2022/10/favicon-96x96-1.png
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.expand
  palette:
    - scheme: default
      primary: '#004c95'
      accent: '#e95f15'
      toggle:
        icon: material/brightness-7
        name: Aldatu modu ilunera
    - scheme: slate
      primary: '#004c95'
      accent: '#e95f15'
      toggle:
        icon: material/brightness-4
        name: Aldatu modu argira
extra_css:
- stylesheets/extra.css
extra_javascript:
- scripts/checkboxes.js
- javascripts/sidebar.js
plugins:
- search
- i18n:
    docs_structure: folder
    languages:
      - locale: eu
        name: Euskara
        default: true
      - locale: es
        name: Español
        nav_translations:
          Hasiera: Inicio
          '1. Sarrera': '1. Introducción'
          '1.1. Zer da Safe Exam Browser?': '1.1. ¿Qué es Safe Exam Browser?'
          '2. Instalazioa': '2. Instalación'
          '2.1. SEB Instalazioa': '2.1. Instalación de SEB'
          '3. Konfigurazioa': '3. Configuración'
          '3.1. Konfigurazioa Oinarrizkoa': '3.1. Configuración Básica'
markdown_extensions:
- admonition
- pymdownx.tasklist:
    clickable_checkbox: true
    custom_checkbox: true
- toc:
    permalink: true
- footnotes
- tables
nav:
  - Hasiera: index.md
  - '1. Sarrera':
    - '1.1. Zer da Safe Exam Browser?': sarrera/zer_da_seb.md
  - '2. Instalazioa':
    - '2.1. SEB Instalazioa': instalazioa/instalatu.md
  - '3. Konfigurazioa':
    - '3.1. Konfigurazioa Oinarrizkoa': konfigurazioa/konfigurazioa_oinarria.md
